In [1]:
import os
import sklearn
import plotly.express as px
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Mall_Customers.csv")
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

# Exploratory Data Analysis

In [3]:
df.info()
print(f'data shape: {df.shape}')

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB
data shape: (200, 5)

In [4]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [CustomerID, Gender, Age, Annual Income (k$), Spending Score (1-100)]
Index: []

In [5]:
px.scatter(df,x='Age',y='Annual Income (k$)').show()

one hot encoding gender column

In [ ]:

df["Gender"] = pd.get_dummies(df["Gender"], drop_first=True, dtype="int64")
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1       1   19                  15                      39
1           2       1   21                  15                      81
2           3       0   20                  16                       6
3           4       0   23                  16                      77
4           5       0   31                  17                      40

feature scaling

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df["Age"] = scaler.fit_transform(df[["Age"]])
df["Annual Income (k$)"] = scaler.fit_transform(df[["Annual Income (k$)"]])
df["Spending Score (1-100)"] = scaler.fit_transform(df[["Spending Score (1-100)"]])
df.head()

   CustomerID  Gender       Age  Annual Income (k$)  Spending Score (1-100)
0           1       1 -1.424569           -1.738999               -0.434801
1           2       1 -1.281035           -1.738999                1.195704
2           3       0 -1.352802           -1.700830               -1.715913
3           4       0 -1.137502           -1.700830                1.040418
4           5       0 -0.563369           -1.662660               -0.395980